Description: Template to deploy IAM Roles and S3 buckets for logs
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "ECS cluster Configuration"
        Parameters: 
          - ProjectName
      - 
        Label:
          default: "Tagging Configuration"
        Parameters:
          - EnvironmentName
Parameters:
  ProjectName:
    Type: String 
    Description: Name for Aurora Cluster DB and EFS. Also used for S3 log bucket naming. 
    Default: drupal
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Test
  LogBucketName:
    Description: Name for Logs Bucket
    Type: String

Mappings:
  RegionMap:
    us-east-1:
      "elbAcc" : "127311923021"
    us-east-2:
      "elbAcc" : "033677994240"
    us-west-1:
      "elbAcc" : "027434742980"
    us-west-2:
      "elbAcc" : "797873946194"
    af-south-1:
      "elbAcc" : "098369216593"
    ca-central-1:
      "elbAcc" : "985666609251"
    eu-central-1:
      "elbAcc" : "054676820928"
    eu-west-1:
      "elbAcc" : "156460612806"
    eu-west-2:
      "elbAcc" : "652711504416"
    eu-south-1:
      "elbAcc" : "635631232127"
    eu-west-3:
      "elbAcc" : "009996457667"
    eu-north-1:
      "elbAcc" : "897822967062"
    ap-east-1:
      "elbAcc" : "754344448648"
    ap-northeast-1:
      "elbAcc" : "582318560864"
    ap-northeast-2:
      "elbAcc" : "600734575887"
    ap-northeast-3:
      "elbAcc" : "383597477331"
    ap-southeast-1:
      "elbAcc" : "114774131450"
    ap-southeast-2:
      "elbAcc" : "783225319266"
    ap-south-1:
      "elbAcc" : "718504428378"
    me-south-1:
      "elbAcc" : "076674570225"
    sa-east-1:
      "elbAcc" : "507241528517"
    us-gov-west-1:
      "elbAcc" : "048591011584"
    us-gov-east-1:
      "elbAcc" : "190560391635"
    eu-south-2:
      "elbAcc" : "000000000000"

Conditions:
  IsLegacyRegion: !Not [!Equals [!FindInMap [RegionMap, !Ref "AWS::Region", "elbAcc"], ""]]

  
Resources:


  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
           - Value: environment
             Key: !Ref EnvironmentName
  
  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              !If 
                - IsLegacyRegion
                - AWS: 
                    Fn::Sub:
                      - "arn:${AWS::Partition}:iam::${ELBAccount}:root"
                      - ELBAccount: !FindInMap [RegionMap, !Ref "AWS::Region", elbAcc]
                - Service: 
                    - "logdelivery.elasticloadbalancing.amazonaws.com"
            Action: s3:PutObject
            Resource: !Sub "${LogBucket.Arn}/*"
 
# =========================== IAM Resources ============================
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Join ['-',[!Ref ProjectName, TaskRole,!Ref AWS::Region]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                 - elasticfilesystem:ClientMount
                 - elasticfilesystem:ClientRootAccess                 
                 - elasticfilesystem:ClientWrite
                Resource: '*'
                Condition:
                  StringEquals:
                    'aws:TagKeys/Name': !Ref ProjectName
              ## Required for ECS Exec
              - Effect: Allow
                Action: 
                 - ssmmessages:CreateControlChannel
                 - ssmmessages:CreateDataChannel
                 - ssmmessages:OpenControlChannel
                 - ssmmessages:OpenDataChannel
                Resource: '*'
            
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Join ['', [!Ref ProjectName, AutoScalingRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref ProjectName, ECSExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: EFSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                  - elasticfilesystem:DescribeMountTargets
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2Role


# ============================== Outputs ===========================
Outputs:
  LogBucketName:
    Description: Name of the Logs bucket
    Value: !Ref LogBucket
    Export:
      Name: !Sub "${AWS::StackName}-LogBucketName"

 ## IAM Exports
  ECSTaskRole:
    Description: Default ECS Task Role
    Value: !Ref ECSTaskRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskRole"
  ECSTaskRoleArn:
    Description: Default ECS Task Role
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskRoleArn"

  AutoScalingRole:
    Description: AutoScaling Role for ECS
    Value: !Ref AutoScalingRole
    Export:
      Name: !Sub "${AWS::StackName}-AutoScalingRole"
  AutoScalingRoleArn:
    Description: Arn of AutoScaling Role for ECS
    Value: !GetAtt AutoScalingRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AutoScalingRoleArn"

  ECSExecutionRole:
    Description: Default ECS Execution Role
    Value: !Ref ECSExecutionRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSExecutionRole"
  ECSExecutionRoleArn:
    Description: Default ECS Execution Role
    Value: !GetAtt ECSExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSExecutionRoleArn"

  EC2Role:
    Description: Role for EC2 Aux Instance
    Value: !Ref EC2Role
    Export:
      Name: !Sub "${AWS::StackName}-EC2Role"
  EC2RoleArn:
    Description: Arn of Role for EC2 Aux Instance
    Value: !GetAtt EC2Role.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EC2RoleArn"
  EC2InstanceProfile:
    Description: Instance Profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-EC2InstanceProfile"